apiVersion: apps/v1
kind: Deployment 
metadata:
  name: petclinic-microservice
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:  
    metadata:
      labels: 
        app: petclinic
    spec:
      initContainers:
        - name: init-db
          image: dts81/petclinic:14504448065
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']      
      containers:
        - name: petclinic-app
          image: dts81/petclinic:14504448065
          ports: 
            - containerPort: 8080        
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "petclinic"            
            - name: DB_USERNAME
              value: "petclinic"        # RDS DB Username is dbadmin     
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-db-password
                  key: db-password           
          livenessProbe:
            exec:
              command: 
                - /bin/sh
                - -c 
                - nc -z localhost 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10 
          resources:
            requests:
              cpu: "500m" 
              memory: "128Mi"
            limits:
              cpu: "1000m"
              memory: "500Mi"      