apiVersion: v1
kind: Service
metadata:
  name: petclinic-app-service
  namespace: petclinic
  labels: 
    app: petclinic
spec:
  type: NodePort
  selector:
    app: petclinic
  ports: 
    - port: 8080
      targetPort: 8080
     
     
